### ISSUE TITLE
Needs more clarification on the kind of install this script does

### ISSUE THREAD

**Issue by abshda** [oleanderxoxo/onidroid#1]
I see the script first installs the Debian chroot environment and then runs the Onionshare installer.

I think it needs to be made clear in the description that Onionshare-cli requires Debian chroot to work.

Individuals can also setup [many different enviornments](https://github.com/EXALAB/Anlinux-Resources/tree/master/Rootfs) before manually installing onionshare-cli to get it working.

**Comment by oleanderxoxo** [comment]
> I see the script first installs the Debian chroot environment and then runs the Onionshare installer.

Yes, the script fetches AnLinux's script to install Debian and then install onionshare from debian default repos

> I think it needs to be made clear in the description that Onionshare-cli requires Debian chroot to work.

It is written in README.md that this script is for termux and as far as I know it works on all phone on which termux can be installed, I was experimenting with other rootfs, mainly Alpine's as it is very light weight and because onionshare version in debian repos is [ancient and insecure](https://web.archive.org/web/20210304225745/https://www.whonix.org/wiki/OnionShare#OnionShare_Version). I tried whonix's approach to install onionshare using [flatpak](https://www.whonix.org/wiki/OnionShare#Flatpak_OnionShare_Installation) but got segmentation fault also it would take up lots of space. It would be amazing if I could make onidroid stand-alone, or could make it work in AnLinux's Alpine chroot.

> Individuals can also setup many different enviornments before manually installing onionshare-cli to get it working.

I chose debian because it was the only lightweight environment on which I was able to install working onionshare, actually Alpine's is just few megs but I was unable to install onionshare on it, I will give it a try again and update the README.

Currently onionshare version on onidroid is same as that on [TailsOS](https://tails.boum.org/) and both should be considered equally [insecure](https://lists.torproject.org/pipermail/tor-dev/2020-May/014322.html) not meant to be used for confidential purposes.

**Comment by abshda** [comment]
> > I see the script first installs the Debian chroot environment and then runs the Onionshare installer.
> 
> Yes, the script fetches AnLinux's script to install Debian and then install onionshare from debian default repos
> 
> > I think it needs to be made clear in the description that Onionshare-cli requires Debian chroot to work.
> 
> It is written in README.md that this script is for termux and as far as I know it works on all phone on which termux can be installed, I was experimenting with other rootfs, mainly Alpine's as it is very light weight and because onionshare version in debian repos is [ancient and insecure](https://web.archive.org/web/20210304225745/https://www.whonix.org/wiki/OnionShare#OnionShare_Version). I tried whonix's approach to install onionshare using [flatpak](https://www.whonix.org/wiki/OnionShare#Flatpak_OnionShare_Installation) but got segmentation fault also it would take up lots of space. It would be amazing if I could make onidroid stand-alone, or could make it work in AnLinux's Alpine chroot.
> 
> > Individuals can also setup many different enviornments before manually installing onionshare-cli to get it working.
> 
> I chose debian because it was the only lightweight environment on which I was able to install working onionshare, actually Alpine's is just few megs but I was unable to install onionshare on it, I will give it a try again and update the README.
> 
> Currently onionshare version on onidroid is same as that on [TailsOS](https://tails.boum.org/) and both should be considered equally [insecure](https://lists.torproject.org/pipermail/tor-dev/2020-May/014322.html) not meant to be used for confidential purposes.

![Screenshot_20210625-164228.jpg](https://user-images.githubusercontent.com/68813419/123416555-56254c00-d5d4-11eb-9b68-85556adb4274.jpg)

I installed onionshare-cli using pip, without chroot environment and it works just fine. And it is the most recent available option.

**Comment by abshda** [comment]
I did see what looks otherwise like an error, but it works without problems.

**Comment by oleanderxoxo** [comment]
> I did see what looks otherwise like an error, but it works without problems.

I have tried this before but it didn't work, years ago, that's why i created this repo, but looks like it works fine, I gave it a try yesterday and it worked for me, apart from these these messy error but they didn't affect the functioning of onionshare-cli. I don't think this repo is of any use now, I should archive it.

Thank you so much @abshda for this information. <333
xoxo
